### ISSUE TITLE
Some basic feedback

### ISSUE THREAD

**Issue by garrensmith** [pipedown/try_out_noise#16]
Hey @vmx and @Damienkatz 
Noisesearch is really cool. I find the syntax pretty intuitive to use. Volker asked me to take a look at the try.noisesearch. I had 20 minutes to play around with it - thanks to a Travis run I had to wait for. Here are some notes:

* Find in Arrays 5 & 6 crashed if I changed .name to .
* Boolean Operators 3 should read “Here is another way to write the same query” just missing `the`. Incorrect spelling for equivalent. Also that sentence could be improved a little. Maybe something like - “Its exactly the same as the previous query, but a little easier to read”
* I would consider moving the “Formating Results as Objects” to earlier, so that we can use that knowledge to play with the queries more.
* Also maybe move the return Field from Nested Objects to earlier
* Aggregrates: Group and Sum: Make firgure into figure

Good luck with your further development.

**Comment by vmx** [comment]
Thanks @garrensmith for the feedback. #17 addresses most of what you proposed. I haven't move the "Return a Field from All Nested Objects" section up as it nicely leads to the aggregates section.

I haven't seen a crash when I changed the arrays steps from `.name` to `.`. Which error message did you get?

**Comment by garrensmith** [comment]
Sorry my mistake. The crash isn't a crash. Just the browser taking really long to load all the data. And display it.
